### ISSUE TITLE
Problem when serializing datetimes

### ISSUE THREAD

**Issue by sarjanen** [DockYard/json_api_assert#31]
I'm completely new to Elixir so guess that I'm the one doing something wrong and need some guidance.
I'm using `ja_serializer` and `ex_machina` for my factories and doing nothing with the default timestamps for inserted_at and updated_at but I get:
```
left:  %{"updated-at" => "2017-03-25T12:16:38.063918"}
right: %{"updated-at" => ~N[2017-03-25 12:16:38.063918]}
```
How to fix this?

**Comment by bcardarella** [comment]
If you're not already, can you try using master? `NaiveDateTime` has already been captured there: https://github.com/DockYard/json_api_assert/blob/master/lib/json_api_assert/serializer.ex#L122 just not released yet.

If you are already using master or the problem persists please let me know and I'll reopen.
