### ISSUE TITLE
Conflicting type for serialized id

### ISSUE THREAD

**Issue by codyjroberts** [DockYard/json_api_assert#4]
Both `Ecto` and [json:api](http://jsonapi.org) use id as a `String`.  Currently `JsonApiAssert.Serializer` is returning id as an `Integer`.  This is requiring me to do something like:

``` elixir
payload = put_in(payload["data"]["id"], model.id) 
```

If this isn't desired, I'd be happy to submit a PR. 🍻

**Comment by bcardarella** [comment]
Yes please :+1:
